### ISSUE TITLE
Maybe a wrong file placement

### ISSUE THREAD

**Issue by laalaguer** [esaulpaugh/headlong#18]
Hi,

I have been using the RLP library with examples, and discovered that:

**FloatingPoint.java** is under package `com.esaulpaugh.headlong.rlp.util`;
But **Integers.java** and **Strings.java** is under package `com.esaulpaugh.headlong.util`;

Maybe it is better to put them together under some package?

**Comment by esaulpaugh** [comment]
I believe they used to be under `rlp` but since I want to avoid `abi` having any imports from `rlp` or vice versa, and the `abi` package depends on `Integers` and `Strings`, I moved them to the `util` package.

**Comment by laalaguer** [comment]
Ah okay. This is expected.
