### ISSUE TITLE
Please update Bouncy Castle

### ISSUE THREAD

**Issue by Neustradamus** [esaulpaugh/headlong#20]
Please update Bouncy Castle, new CVEs
- https://www.bouncycastle.org/
- https://www.bouncycastle.org/releasenotes.html
- http://www.bouncycastle.org/latest_releases.html
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncy%20castle
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncycastle
- https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

**Comment by esaulpaugh** [comment]
https://github.com/esaulpaugh/headlong/releases/tag/v4.1.0

**Comment by Neustradamus** [comment]
@esaulpaugh: Thanks!

**Comment by Neustradamus** [comment]
@esaulpaugh: I see that there are two version in the code: 1.68 and 1.69, can you look to have only 1.69?
- https://github.com/esaulpaugh/headlong/search?q=bouncycastle

**Comment by esaulpaugh** [comment]
https://github.com/esaulpaugh/headlong/commit/b011e2a0e1170662dc29bb9b61dcb4ee3ff0296c

**Comment by Neustradamus** [comment]
@esaulpaugh: Good job, thanks!
