### ISSUE TITLE
ask for helf

### ISSUE THREAD

**Issue by zouqingfeng** [esaulpaugh/headlong#27]
Can you tell me the process of calling  ABIV2 contract function on the  chain of blocks ?

**Comment by esaulpaugh** [comment]
function arguments are encoded into `calldata`. that's what headlong does.

Other tools can encode and sign the transaction that contains the `calldata`. then the transaction has to be broadcast to the network by an ethereum node.

web3j can be used to do the transaction encoding and broadcasting

**Comment by zouqingfeng** [comment]
so , I can use web3j to call on  ethereum node and then get headlong to call funtion. Finally , do the transaction by web3j . That right ?

**Comment by esaulpaugh** [comment]
broadcasting through an ethereum node is the final step. encoding the function call with headlong should be the first step.

web3j docs say they have "Support for Alchemy and Infura, so you don't have to run an Ethereum client yourself"
