### ISSUE TITLE
`TupleType.subTupleType` not unwrapping tuple of a single tuple

### ISSUE THREAD

**Issue by devictr** [esaulpaugh/headlong#31]
Hi,

I've noticed that [this function](https://github.com/esaulpaugh/headlong/blob/master/src/main/java/com/esaulpaugh/headlong/abi/TupleType.java#L335), when called with on a `Tuple` that looks like this `((address,int256))` and this manifest: `[true]`, will still return `((address,int256))` even though I would expect to get `(address,int256)`.
I'd be happy to help fix this issue, if it is actually an issue 🙂

**Comment by esaulpaugh** [comment]
`subtupleType` with a manifest of all `true` values should return a `TupleType` equal to the input `TupleType`. An all-true manifest is similar to using `str.substring(0, str.length())`.

It was originally designed for separating indexed and non-indexed event parameters.

I will see about adding better documentation.

**Comment by esaulpaugh** [comment]
In addition to adding documentation, I have decided to rename `TupleType::subTupleType` to `select` and `TupleType::subTupleTypeNegative` to `exclude`.

**Comment by devictr** [comment]
Ah good to know! Thank you

**Comment by esaulpaugh** [comment]
I just added type inference to `TupleType::get`. Subtuples should now be accessible like this:

`TupleType outer = TupleType.parse("((address,int256))");`
`TupleType inner = outer.get(0);`
`assertEquals(TupleType.parse("(address,int)"), inner);`

**Comment by devictr** [comment]
Even better! Thanks
