### ISSUE TITLE
`Event` decoding API

### ISSUE THREAD

**Issue by devictr** [esaulpaugh/headlong#32]
Hi @esaulpaugh,

I initially asked on gitter, but thought I'd create an issue here directly.
Is there a way to decode events, like there is `Function.decodeCall()` ? 
If not, I'd be happy to help implement that.

I really appreciate all the work you've done for this lib, it saved me so much time and the API is very well designed.

**Comment by esaulpaugh** [comment]
Thanks!

I've been confused about how exactly to interpret the abi-spec with regards to events (and to some extent, packed encoding). Ideally headlong would be a full and faithful implementation of https://docs.soliditylang.org/en/latest/abi-spec.html and I haven't had much time to test against other frameworks or solidity.

I'm not looking to create a whole event-handling framework, but if you could write some low-level methods which would facilitate the building of such frameworks on top of headlong, that would be very helpful.

**Comment by devictr** [comment]
Sounds good. I think I will implement something that looks like what `ethereumj` does [here](https://github.com/ethereum/ethereumj/blob/develop/ethereumj-core/src/main/java/org/ethereum/solidity/Abi.java#L287), but using your types and helper functions of course

**Comment by devictr** [comment]
PR here: https://github.com/esaulpaugh/headlong/pull/33

**Comment by esaulpaugh** [comment]
new release v6.0.0 coming soon
