### ISSUE TITLE
Encode abi params

### ISSUE THREAD

**Issue by tomasz90** [esaulpaugh/headlong#39]
Hi again :)

Is there possibility to encode abi params without function name itself? My workaround is empting first 4 bytes   for example:

```
val args = Tuple(Address.wrap("0x5757371414417b8C6CAad45bAeF941aBc7d3Ab32"), 5)
val f = Function("(address,uint8)")
val callData = f.encodeCall(args)
```
it gives: `0xd6ec702b0000000000000000000000005757371414417b8c6caad45baef941abc7d3ab320000000000000000000000000000000000000000000000000000000000000005`
then I clear first bytes. I bet that this library have such functionality.

Thanks!

**Comment by esaulpaugh** [comment]
Yes if you have a `TupleType` reference you can call the `encode` method.

If you have a `Function` you can call `getInputs` to get the params `TupleType`

You can also use `TupleType::parse` or `TypeFactory::create` giving the signature of the params type.

For example passing the String "(int,bool,string)" would create a `TupleType` with three elements.
